---

- hosts: all
  gather_facts: no
  tasks:

    - apt:
        name:
          - docker.io
          - python3-docker
        update_cache: yes
        cache_valid_time: 604800 # 1 week

    - service:
        name: docker
        state: started
        enabled: yes
